"""empty message

Revision ID: 0878709d3ee1
Revises: bc9e0a1d093f
Create Date: 2021-06-12 19:56:50.130367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0878709d3ee1'
down_revision = 'bc9e0a1d093f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Reaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Reaction')
    # ### end Alembic commands ###
